# Generated by Django 3.2 on 2023-12-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('youdu_id', models.IntegerField(null=True, verbose_name='有度ID')),
                ('level', models.IntegerField(default=1, verbose_name='部门等级')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='users.organization')),
            ],
            options={
                'db_table': 'users_organization',
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=32, verbose_name='花名')),
                ('name', models.CharField(default='', max_length=32, verbose_name='真名')),
                ('email', models.CharField(max_length=128, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=18, null=True, verbose_name='电话')),
                ('sex', models.IntegerField(default=1, verbose_name='性别')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_set', to='users.organization')),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
    ]
