# Generated by Django 3.2 on 2023-12-08 11:16

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='业务线名称')),
                ('label', models.CharField(max_length=32, verbose_name='业务线别名')),
                ('platform', models.CharField(max_length=32, verbose_name='业务线平台')),
                ('description', models.CharField(max_length=255, verbose_name='业务线描述')),
            ],
            options={
                'db_table': 'apps_business',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='产品线名称')),
                ('label', models.CharField(max_length=32, verbose_name='产品线别名')),
                ('description', models.CharField(max_length=255, verbose_name='产品线描述')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_product', to='project.businessesmodel', verbose_name='业务线ID')),
            ],
            options={
                'db_table': 'apps_product',
            },
        ),
        migrations.CreateModel(
            name='ApplicationModelM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='应用名')),
                ('lang', models.CharField(choices=[('JAVA', 'java'), ('GOLANG', 'go'), ('PHP', 'PHP'), ('PYTHON', 'python'), ('NODE', 'node')], max_length=18, verbose_name='语言')),
                ('level', models.CharField(choices=[('S级', 's'), ('A级', 'a'), ('B级', 'b')], max_length=8, verbose_name='应用等级')),
                ('mold', models.CharField(choices=[('物理应用', 'phyiscs'), ('虚拟应用', 'virtural')], max_length=18, verbose_name='应用类型')),
                ('cost_mode', models.CharField(choices=[('计算型', 'cpu'), ('内存型', 'memory'), ('磁盘型', 'disk')], max_length=18, verbose_name='成本模型')),
                ('is_docker', models.CharField(choices=[('容器应用', 'docker'), ('常规应用', 'common')], max_length=18, verbose_name='容器应用')),
                ('health', djongo.models.fields.JSONField(default={}, verbose_name='巡检健康度信息')),
                ('handle_info', models.CharField(default='', max_length=300, verbose_name='服务健康度处理意见')),
                ('description', models.CharField(default='', max_length=255, verbose_name='备注信息')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_set', to='users.usersmodel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_set', to='users.usersmodel')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='users.usersmodel')),
            ],
            options={
                'db_table': 'apps_application',
            },
        ),
    ]
